### ISSUE TITLE
Objective and Vision for mpvKt

### ISSUE THREAD

**Issue by Brajesh3** [abdallahmehiz/mpvKt#44]
Will this project follow the same minimalistic approach as the original mpv-android, acting as a simple frontend for a media player, or will it expand its capabilities? Some potential features could include:

- Support for video thumbnails and a library view for easy media navigation.
- A special player screen designed specifically for music files.
- Additional UI enhancements for a more engaging user experience.

Clarification on these points would help guide contributions and feature requests.

**Comment by abdallahmehiz** [comment]
> Will this project follow the same minimalistic approach as the original mpv-android.

For the most part, I want it to be and stay that way by straying from complex, niche features, but I also want to make it easy to use and customize for newer, none tech savvy people so I am kind of discovering that thin line between minimalism and ease of use.
There are some features that I am not sure about committing to try adding them yet like #34 since it adds a lot of complexity to the codebase with not much value to most users.

as for the features you listed:
> Support for video thumbnails and a library view for easy media navigation.

Android's permissions are making this a bit annoying to make so it's not a priority right now, but It's not out of this project's scope.

> A special player screen designed specifically for music files.

No, there are plenty of good open source music players online that do the job perfectly fine, most users would probably like to use those instead.

> Additional UI enhancements for a more engaging user experience.

Of course, as long as these features don't get too into the way of consuming media and actually provide something of value to most users.
